### ISSUE TITLE
Coordinator.xml has shouldStart variable name in <sla:should-end></sla:should-end> element

### ISSUE THREAD

**Issue by galacticgumshoe** [SimonJPegg/scoozie#28]
Issue is with this line: https://github.com/SimonJPegg/scoozie/blob/bff376c2a0b2b531059a0dcd5988ba465f7df1c9/src/main/scala/org/antipathy/scoozie/sla/OozieSLA.scala#L105

Results in this sla:
```xml
    <sla:info>
        ...
        <sla:should-end>${test_dip_workflow_sla_shouldStart}</sla:should-end>
        ...
    </sla:info>
```

**Comment by SimonJPegg** [comment]
Thanks for the PR.  closing this issue.
